"""Mermaid, DOT, JSON, and self-contained HTML renderers for a graph."""
from __future__ import annotations

import html
import json
from importlib import resources
from typing import Dict


def to_mermaid(graph: Dict) -> str:
    """Render a graph as a Mermaid flowchart."""
    nodes = graph["nodes"]
    edges = graph["edges"]
    meta = graph.get("metadata", {})
    scope = meta.get("scope", "graph")
    lines = [f"graph {'TB' if scope in ('impact', 'module', 'repo') else 'LR'}"]
    # Sanitize node ids (Mermaid ids can't contain some chars).
    safe = {}
    for n in nodes:
        sid = "".join(c if c.isalnum() else "_" for c in n["id"])[:30]
        safe[n["id"]] = sid
        label = _mermaid_esc(n["id"])
        shape = _shape_for_kind(n.get("kind", ""))
        lines.append(f'    {sid}{shape.format(label)}')
    lines.append("")
    for e in edges:
        s = safe.get(e["source"], _sanitize(e["source"]))
        t = safe.get(e["target"], _sanitize(e["target"]))
        label = e.get("label") or ""
        arrow = f' -->|"{_mermaid_esc(label)}"|' if label else " -->"
        if s and t:
            lines.append(f"    {s}{arrow}{t}")
    return "\n".join(lines) + "\n"


def to_dot(graph: Dict) -> str:
    """Render a graph as Graphviz DOT."""
    nodes = graph["nodes"]
    edges = graph["edges"]
    lines = ["digraph cairn {"]
    lines.append('    rankdir=LR;')
    lines.append('    node [shape=box, style=rounded];')
    safe = {}
    for n in nodes:
        sid = _sanitize(n["id"])
        safe[n["id"]] = sid
        lines.append(f'    {sid} [label="{_esc(n["id"])}"];')
    for e in edges:
        s = safe.get(e["source"], _sanitize(e["source"]))
        t = safe.get(e["target"], _sanitize(e["target"]))
        label = e.get("label") or ""
        attr = f' [label="{_esc(label)}"]' if label else ""
        if s and t:
            lines.append(f"    {s} -> {t}{attr};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def to_json(graph: Dict) -> str:
    """Render a graph as JSON (nodes, edges, metadata)."""
    return json.dumps(graph, indent=2, default=str)


def to_html(graph: Dict) -> str:
    """Render a graph as one self-contained HTML document.

    The page inlines the dashboard's local vis-network viewer, the graph
    JSON escaped for a script context, and the Mermaid source as a text
    fallback; it references no network assets.
    """
    meta = graph.get("metadata", {})
    focus = meta.get("symbol") or meta.get("module") or meta.get("repo") or ""
    scope = meta.get("scope", "graph")
    title = html.escape(f"cairn viz — {scope}: {focus}" if focus else f"cairn viz — {scope}")
    return "\n".join([
        "<!doctype html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>{title}</title>",
        f"<style>{_HTML_CSS}</style>",
        "</head>",
        "<body>",
        f"<h1>{title}</h1>",
        '<div id="cairn-graph" aria-label="Selected graph scope"></div>',
        "<details>",
        "<summary>Mermaid source</summary>",
        f'<pre class="mermaid-source">{_html_text(to_mermaid(graph))}</pre>',
        "</details>",
        '<script type="application/json" id="cairn-graph-data">',
        _script_json(graph),
        "</script>",
        "<script>",
        _viewer_js(),
        "</script>",
        f"<script>{_HTML_BOOTSTRAP}</script>",
        "</body>",
        "</html>",
    ]) + "\n"


def embed(graph: Dict) -> str:
    """Wrap Mermaid output in an OKF-compatible markdown block."""
    meta = graph.get("metadata", {})
    title = f"{meta.get('scope','graph')}: {meta.get('symbol') or meta.get('module') or meta.get('repo','')}"
    from datetime import datetime, timezone

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out = [f"## {title}", "", "```mermaid"]
    out.append(to_mermaid(graph).rstrip())
    out.append("```")
    out.append("")
    out.append(f"*Generated by `cairn viz` on {ts}*")
    return "\n".join(out) + "\n"


# --- helpers -------------------------------------------------------------

def _sanitize(name: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in str(name))[:30]


def _esc(s: str) -> str:
    return str(s).replace('"', '\\"')


def _mermaid_esc(text: str) -> str:
    """Escape text for use inside a Mermaid node/edge label.

    Mermaid node shapes use ``[...]`` / ``[[...]]`` / ``(...)`` with the label
    rendered raw, and edge labels sit inside ``|"..."|``. Characters like
    ``]``, ``[``, ``|``, ``"``, and newlines terminate or corrupt the label.
    DOT has its own ``_esc``; this is the Mermaid equivalent.
    """
    return (
        (text or "")
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("|", "\\|")
        .replace("[", "\\[")
        .replace("]", "\\]")
        .replace("\n", " ")
    )


def _script_json(value) -> str:
    """JSON escaped for embedding inside a ``<script>`` element."""
    return (
        json.dumps(value, default=str)
        .replace("<", "\\u003c")
        .replace(" ", "\\u2028")
        .replace(" ", "\\u2029")
    )


def _html_text(text: str) -> str:
    """Escape text for an HTML text node while keeping ``-->`` readable."""
    return text.replace("&", "&amp;").replace("<", "&lt;")


def _viewer_js() -> str:
    """The dashboard's bundled vis-network build, without its source-map pointer."""
    text = (
        resources.files("cairn.dashboard")
        .joinpath("static/vis-network.min.js")
        .read_text(encoding="utf-8")
    )
    return "\n".join(
        line
        for line in text.splitlines()
        if not line.startswith("//# sourceMappingURL=")
    )


_HTML_CSS = """
:root { color-scheme: light dark; }
body { margin: 0; padding: 1rem; font: 14px/1.5 system-ui, sans-serif; }
#cairn-graph { height: 75vh; border: 1px solid #888; border-radius: 8px; }
details { margin-top: 1rem; }
pre { overflow-x: auto; padding: 0.75rem; border: 1px solid #888; border-radius: 8px; }
"""

_HTML_BOOTSTRAP = """
(function () {
  var payload = JSON.parse(
    document.getElementById("cairn-graph-data").textContent
  );
  var nodes = payload.nodes.map(function (n) {
    var tip = n.kind ? n.id + " (" + n.kind + ")" : n.id;
    return { id: n.id, label: n.id, title: tip };
  });
  var edges = payload.edges
    .filter(function (e) { return e.source && e.target; })
    .map(function (e) {
      return {
        from: e.source,
        to: e.target,
        label: e.label || e.kind || undefined,
        arrows: "to",
      };
    });
  new vis.Network(
    document.getElementById("cairn-graph"),
    { nodes: nodes, edges: edges },
    { interaction: { hover: true } }
  );
})();
"""


_SHAPES = {
    "class": "[{}]",
    "interface": "[[{}]]",
    "enum": "({})",
    "function": "({})",
    "method": "({})",
    "property": "[{}]",
    "repo": "[[{}]]",
    "module": "[{}/]",
}


def _shape_for_kind(kind: str):
    return _SHAPES.get(kind, "[{}]")
