"""Git hook installer: installs post-commit hooks in each repo for auto graph updates."""
from __future__ import annotations

import re
import stat
from typing import List

from ..graph.scanner import resolve_repo_path

# SECURITY: repo names are interpolated into a bash script (POST_COMMIT_TEMPLATE)
# that is executed on every `git commit`. Repo names arrive unsanitized from
# scanner.discover_repos() (child.name of a workspace subdirectory), so a
# maliciously-named workspace subdir such as `foo"; rm -rf $HOME; echo "` would
# inject arbitrary shell. This strict allowlist rejects anything that is not a
# safe filename token before it can reach the template.
_REPO_NAME_RE = re.compile(r"^[A-Za-z0-9._-]+$")


def _validate_repo_name(repo: str) -> str:
    """Reject repo names that are unsafe to interpolate into the bash hook.

    Raises ValueError if `repo` contains any character outside
    [A-Za-z0-9._-]. Returns `repo` unchanged on success.
    """
    if not isinstance(repo, str) or not _REPO_NAME_RE.match(repo):
        raise ValueError(
            f"Invalid repo name (security: shell-injection guard): {repo!r}"
        )
    return repo


POST_COMMIT_TEMPLATE = """#!/bin/bash
# Auto-generated by cairn (cairn hooks install)
# Runs an incremental graph update after every commit. cairn resolves the central
# store for this workspace from cwd (ancestor walk), so no paths are baked in.
cairn update --repo "{repo}" > /dev/null 2>&1 &
cairn validate-paths --mark > /dev/null 2>&1 &
"""


def install_hooks(repos: List[str], workspace: str, cairn_dir: str = "") -> List[str]:
    """Install post-commit hooks in each repo. Returns list of installed repo names.

    `cairn_dir` is accepted but unused: the hook invokes `cairn` (resolved on
    PATH), which finds the store via workspace context.

    Raises ValueError if any repo name fails the shell-injection guard.
    """
    # Validate ALL repos up front (before any hook is written) so a single bad
    # name is rejected atomically rather than leaving a half-installed state.
    for repo in repos:
        _validate_repo_name(repo)

    installed = []
    for repo in repos:
        hook_path = resolve_repo_path(workspace, repo) / ".git" / "hooks" / "post-commit"
        hook_path.parent.mkdir(parents=True, exist_ok=True)
        # Don't overwrite a non-cairn hook.
        if hook_path.exists() and "cairn" not in hook_path.read_text():
            continue
        hook_path.write_text(
            POST_COMMIT_TEMPLATE.format(repo=repo),
            encoding="utf-8",
        )
        hook_path.chmod(hook_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        installed.append(repo)
    return installed


def uninstall_hooks(repos: List[str], workspace: str) -> List[str]:
    """Remove cairn post-commit hooks. Returns list of uninstalled repo names."""
    removed = []
    for repo in repos:
        hook_path = resolve_repo_path(workspace, repo) / ".git" / "hooks" / "post-commit"
        if hook_path.exists() and "cairn" in hook_path.read_text():
            hook_path.unlink()
            removed.append(repo)
    return removed
