"""Git hook installer: installs post-commit and post-checkout hooks in each repo for auto graph updates."""
from __future__ import annotations

import re
import stat
from typing import List

from ..graph.scanner import discover_repos, repository_id, resolve_repo_path
from ..paths import cairn_home_env

# Repository ids are interpolated into a bash script. Slash-separated nested
# ids are allowed; every segment must contain only safe filename characters.
_REPO_NAME_RE = re.compile(r"^[A-Za-z0-9._-]+(?:/[A-Za-z0-9._-]+)*$")


def _validate_repo_name(repo: str) -> str:
    """Reject repo names that are unsafe to interpolate into the bash hook.

    Raises ValueError for a repository id outside the shell-safe allowlist.
    """
    if not isinstance(repo, str) or not _REPO_NAME_RE.fullmatch(repo):
        raise ValueError(
            f"Invalid repo name (security: shell-injection guard): {repo!r}"
        )
    return repo


POST_COMMIT_TEMPLATE = """#!/bin/bash
# Auto-generated by cairn (cairn hooks install)
# Runs an incremental graph update over the committed range after every commit.
# cairn resolves the central store for this workspace from cwd (ancestor walk);
# when the store home is not the default, the export line above pins it for
# this script.
prev=$(git rev-parse -q --verify 'HEAD@{{1}}')
if [ -n "$prev" ]; then
  range="${{prev}}..HEAD"
else
  range="$(git hash-object -t tree /dev/null)..HEAD"
fi
cairn update --repo "{repo}" --diff-ref "$range" > /dev/null 2>&1 &
cairn validate-paths --mark > /dev/null 2>&1 &
"""


POST_CHECKOUT_TEMPLATE = """#!/bin/bash
# Auto-generated by cairn (cairn hooks install)
# Runs an incremental graph update over the checked-out range on branch
# switches. cairn resolves the central store for this workspace from cwd
# (ancestor walk); when the store home is not the default, the export line
# above pins it for this script.
if [ "$3" = "1" ]; then
  cairn update --repo "{repo}" --diff-ref "$1..$2" > /dev/null 2>&1 &
fi
"""


def _render_hook(template: str, repo: str) -> str:
    """Template for `repo`, with one quoted
    `export CAIRN_HOME="<path>"` line right after the shebang when the
    effective home is non-default. Default home keeps the hook
    byte-identical to the bare template.
    """
    rendered = template.format(repo=repo)
    env = cairn_home_env()
    if not env:
        return rendered
    path = env["CAIRN_HOME"]
    shebang, _, rest = rendered.partition("\n")
    return f'{shebang}\nexport CAIRN_HOME="{path}"\n{rest}'


def _render_post_commit(repo: str) -> str:
    """POST_COMMIT_TEMPLATE for `repo` via _render_hook."""
    return _render_hook(POST_COMMIT_TEMPLATE, repo)


def _render_post_checkout(repo: str) -> str:
    """POST_CHECKOUT_TEMPLATE for `repo` via _render_hook."""
    return _render_hook(POST_CHECKOUT_TEMPLATE, repo)


_HOOK_RENDERERS = {
    "post-commit": _render_post_commit,
    "post-checkout": _render_post_checkout,
}


NO_GIT_REPOS_GUIDANCE = (
    "No git repositories found in this workspace — cairn git hooks install "
    "into .git/hooks, so run `git init` in your repository root first."
)


def discover_hook_repos(workspace: str) -> List[str]:
    """Repository ids under `workspace` that install_hooks/uninstall_hooks accept."""
    return [repository_id(r) for r in discover_repos(workspace)]


def install_hooks(repos: List[str], workspace: str) -> List[str]:
    """Install cairn post-commit and post-checkout hooks in each repo.
    Returns list of installed repo names.

    Raises ValueError if any repo name fails the shell-injection guard.
    """
    # Validate ALL repos up front (before any hook is written) so a single bad
    # name is rejected atomically rather than leaving a half-installed state.
    for repo in repos:
        _validate_repo_name(repo)

    installed = []
    for repo in repos:
        hooks_dir = resolve_repo_path(workspace, repo) / ".git" / "hooks"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        touched = False
        for hook_name, render in _HOOK_RENDERERS.items():
            hook_path = hooks_dir / hook_name
            # Don't overwrite a non-cairn hook.
            if hook_path.exists() and "cairn" not in hook_path.read_text():
                continue
            hook_path.write_text(render(repo), encoding="utf-8")
            hook_path.chmod(hook_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
            touched = True
        if touched:
            installed.append(repo)
    return installed


def uninstall_hooks(repos: List[str], workspace: str) -> List[str]:
    """Remove cairn post-commit and post-checkout hooks. Returns list of
    uninstalled repo names."""
    removed = []
    for repo in repos:
        hooks_dir = resolve_repo_path(workspace, repo) / ".git" / "hooks"
        touched = False
        for hook_name in _HOOK_RENDERERS:
            hook_path = hooks_dir / hook_name
            if hook_path.exists() and "cairn" in hook_path.read_text():
                hook_path.unlink()
                touched = True
        if touched:
            removed.append(repo)
    return removed
