"""Mermaid, DOT, and JSON renderers for a {nodes, edges, metadata} graph."""
from __future__ import annotations

import json
from typing import Dict


def to_mermaid(graph: Dict) -> str:
    """Render a graph as a Mermaid flowchart."""
    nodes = graph["nodes"]
    edges = graph["edges"]
    meta = graph.get("metadata", {})
    scope = meta.get("scope", "graph")
    lines = [f"graph {'TB' if scope in ('impact', 'module', 'repo') else 'LR'}"]
    # Sanitize node ids (Mermaid ids can't contain some chars).
    safe = {}
    for n in nodes:
        sid = "".join(c if c.isalnum() else "_" for c in n["id"])[:30]
        safe[n["id"]] = sid
        label = _mermaid_esc(n["id"])
        shape = _shape_for_kind(n.get("kind", ""))
        lines.append(f'    {sid}{shape.format(label)}')
    lines.append("")
    for e in edges:
        s = safe.get(e["source"], _sanitize(e["source"]))
        t = safe.get(e["target"], _sanitize(e["target"]))
        label = e.get("label") or ""
        arrow = f' -->|"{_mermaid_esc(label)}"|' if label else " -->"
        if s and t:
            lines.append(f"    {s}{arrow}{t}")
    return "\n".join(lines) + "\n"


def to_dot(graph: Dict) -> str:
    """Render a graph as Graphviz DOT."""
    nodes = graph["nodes"]
    edges = graph["edges"]
    lines = ["digraph codegraph {"]
    lines.append('    rankdir=LR;')
    lines.append('    node [shape=box, style=rounded];')
    safe = {}
    for n in nodes:
        sid = _sanitize(n["id"])
        safe[n["id"]] = sid
        lines.append(f'    {sid} [label="{_esc(n["id"])}"];')
    for e in edges:
        s = safe.get(e["source"], _sanitize(e["source"]))
        t = safe.get(e["target"], _sanitize(e["target"]))
        label = e.get("label") or ""
        attr = f' [label="{_esc(label)}"]' if label else ""
        if s and t:
            lines.append(f"    {s} -> {t}{attr};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def to_json(graph: Dict) -> str:
    """Render a graph as JSON (nodes, edges, metadata)."""
    return json.dumps(graph, indent=2, default=str)


def embed(graph: Dict) -> str:
    """Wrap Mermaid output in an OKF-compatible markdown block."""
    meta = graph.get("metadata", {})
    title = f"{meta.get('scope','graph')}: {meta.get('symbol') or meta.get('module') or meta.get('repo','')}"
    from datetime import datetime, timezone

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out = [f"## {title}", "", "```mermaid"]
    out.append(to_mermaid(graph).rstrip())
    out.append("```")
    out.append("")
    out.append(f"*Generated by `cg viz` on {ts}*")
    return "\n".join(out) + "\n"


# --- helpers -------------------------------------------------------------

def _sanitize(name: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in str(name))[:30]


def _esc(s: str) -> str:
    return str(s).replace('"', '\\"')


def _mermaid_esc(text: str) -> str:
    """Escape text for use inside a Mermaid node/edge label.

    Mermaid node shapes use ``[...]`` / ``[[...]]`` / ``(...)`` with the label
    rendered raw, and edge labels sit inside ``|"..."|``. Characters like
    ``]``, ``[``, ``|``, ``"``, and newlines terminate or corrupt the label.
    DOT has its own ``_esc``; this is the Mermaid equivalent.
    """
    return (
        (text or "")
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("|", "\\|")
        .replace("[", "\\[")
        .replace("]", "\\]")
        .replace("\n", " ")
    )


_SHAPES = {
    "class": "[{}]",
    "interface": "[[{}]]",
    "enum": "({})",
    "function": "({})",
    "method": "({})",
    "property": "[{}]",
    "repo": "[[{}]]",
    "module": "[{}/]",
}


def _shape_for_kind(kind: str):
    return _SHAPES.get(kind, "[{}]")
