#!/usr/bin/env python3
"""Generate the parser conformance table into docs/indexing.md.

Renders one row per golden-fixtured language from tests/fixtures/golden/:
symbol/edge/import coverage derived from each expected.json. The committed
table is kept fresh by tests/test_conformance_table.py.

Usage:
    .venv/bin/python scripts/gen_conformance_table.py [--check]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from tests.fixtures.golden.regenerate import GOLDEN_DIR, LANG_CONFIG  # noqa: E402

DOC = REPO_ROOT / "docs" / "indexing.md"
BEGIN = "<!-- conformance:begin (generated by scripts/gen_conformance_table.py) -->"
END = "<!-- conformance:end -->"

_CALL_KINDS = {"calls"}
_HIERARCHY_KINDS = {"extends", "implements"}


def _row(lang: str) -> dict:
    expected = json.loads(
        (GOLDEN_DIR / lang / "expected.json").read_text(encoding="utf-8")
    )
    kinds = {e["kind"] for e in expected["edges"]}
    calls = bool(kinds & _CALL_KINDS)
    hierarchy = bool(kinds & _HIERARCHY_KINDS)
    imports = bool(expected.get("imports"))
    tiers = []
    if not imports:
        tiers.append("no import edges")
    if not hierarchy:
        tiers.append("no hierarchy edges")
    if not calls:
        tiers.append("symbols only")
    return {
        "lang": lang,
        "symbols": len(expected["symbols"]),
        "edges": len(expected["edges"]),
        "imports": len(expected.get("imports", [])),
        "calls": calls,
        "hierarchy": hierarchy,
        "import_edges": imports,
        "tier": "; ".join(tiers) if tiers else "green",
    }


def render_table() -> str:
    rows = [_row(lang) for lang in sorted(LANG_CONFIG)]
    lines = [
        "| Language | Golden | Symbols | Edges | Imports | Status |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['lang']} | green | {r['symbols']} | {r['edges']} | "
            f"{r['imports']} | {r['tier']} |"
        )
    return "\n".join(lines)


def main() -> int:
    table = render_table()
    if "--check" in sys.argv:
        text = DOC.read_text(encoding="utf-8")
        try:
            start, end = text.index(BEGIN), text.index(END)
        except ValueError:
            print("conformance markers missing from docs/indexing.md")
            return 1
        committed = text[start + len(BEGIN) : end].strip()
        if committed != table:
            print("committed conformance table is stale; regenerate with "
                  "scripts/gen_conformance_table.py")
            return 1
        print(f"conformance table fresh ({len(LANG_CONFIG)} rows)")
        return 0
    text = DOC.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print("conformance markers missing from docs/indexing.md")
        return 1
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    DOC.write_text(f"{head}{BEGIN}\n\n{table}\n\n{END}{tail}", encoding="utf-8")
    print(f"wrote {len(LANG_CONFIG)} rows to docs/indexing.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
