#!/bin/bash
# scripts/install-hooks.sh
# Installs git post-commit hooks in all repos for automatic graph updates.
# Alternatively, use: cairn hooks install

set -e

REPOS=(
  "ai-services"
  "be-core-ui"
  "be-sdk"
  "customer-android"
  "driver-android"
  "mobiletool"
)

# Resolve repo root from this script's location (scripts/ -> parent dir).
BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CAIRN="$BASE"

for repo in "${REPOS[@]}"; do
  HOOK="$BASE/$repo/.git/hooks/post-commit"

  cat > "$HOOK" << EOF
#!/bin/bash
# Auto-generated by cairn (scripts/install-hooks.sh)
# Runs an incremental graph update after every commit.
cd "$CAIRN" 2>/dev/null && source .venv/bin/activate 2>/dev/null && \\
  cairn update --repo "$repo" > /dev/null 2>&1 &
EOF

  chmod +x "$HOOK"
  echo "Installed post-commit hook in $repo"
done

echo ""
echo "Git hooks installed. Graph will auto-update after each commit."
echo "To remove: cairn hooks uninstall"
