#!/usr/bin/env bash
# Regenerate src/cairn/parsers/_scip_pb2.py from upstream sourcegraph/scip's
# scip.proto. This is a DEV-ONLY step -- the generated stub is checked in so
# end users installing cairn-intel[scip] only need the `protobuf` runtime.
#
# Why this exists: no PyPI package ships Sourcegraph SCIP protobuf bindings.
# (The `scip` name on PyPI is an unrelated bioimaging library.) We vendor a
# generated stub instead, paired with the real `protobuf` runtime package --
# the same approach googleapis-common-protos uses.
#
# Usage:
#   scripts/regen_scip_pb2.sh [commit-sha]     # default: upstream HEAD
#
# After regenerating:
#   1. Re-pin the [scip] extra's `protobuf` floor in pyproject.toml to >= the
#      version ValidateProtobufRuntimeVersion() requires (printed below).
#   2. Update the provenance comment at the top of _scip_pb2.py with the new
#      commit SHA + generator versions.
#   3. Commit _scip_pb2.py + pyproject.toml together -- never let them drift.
set -euo pipefail

COMMIT="${1:-HEAD}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "→ fetching scip.proto @ $COMMIT"
URL="https://raw.githubusercontent.com/sourcegraph/scip/${COMMIT}/scip.proto"
if [ "$COMMIT" = "HEAD" ]; then
    curl -fsSL "$URL" -o "$WORK/scip.proto"
    # Resolve HEAD to a SHA for the provenance pin.
    SHA="$(curl -fsSL "https://api.github.com/repos/sourcegraph/scip/commits?path=scip.proto&per_page=1" \
           | python3 -c "import sys,json;print(json.load(sys.stdin)[0]['sha'])")"
else
    URL="https://raw.githubusercontent.com/sourcegraph/scip/${COMMIT}/scip.proto"
    curl -fsSL "$URL" -o "$WORK/scip.proto"
    SHA="$COMMIT"
fi
echo "  resolved SHA: $SHA"

echo "→ generating _scip_pb2.py (needs grpcio-tools)"
cp "$WORK/scip.proto" "$WORK/"
( cd "$WORK" && python3 -m grpc_tools.protoc -I. --python_out=. scip.proto )

echo "→ installing to $REPO_ROOT/src/cairn/parsers/_scip_pb2.py"
# Preserve the provenance header; protoc's output starts with its own header
# we replace wholesale.
PROTO_VER="$(python3 -c 'import google.protobuf; print(google.protobuf.__version__)')"
GRPC_TOOLS_VER="$(python3 -c 'import grpc_tools; print(grpc_tools.__version__)' 2>/dev/null || echo 'unknown')"

cat > "$REPO_ROOT/src/cairn/parsers/_scip_pb2.py" <<HEADER
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scip.proto
# Protobuf Python Version: ${PROTO_VER}
#
# ── cairn provenance ──────────────────────────────────────────────────────
# This file is a vendored, checked-in stub generated from upstream
# sourcegraph/scip's scip.proto (no PyPI package ships SCIP bindings; see
# pyproject.toml [scip] extra). Regenerate via scripts/regen_scip_pb2.sh --
# never edit by hand.
#
#   upstream: https://github.com/sourcegraph/scip/blob/main/scip.proto
#   commit:   ${SHA}
#   generator: grpcio-tools ${GRPC_TOOLS_VER} (protoc) + protobuf ${PROTO_VER} runtime
#
# The [scip] extra's protobuf floor MUST stay >= the version this stub's
# ValidateProtobufRuntimeVersion() check below requires; re-pin together
# whenever grpcio-tools is upgraded.
HEADER
# Append the body of protoc's output (everything after its header comment).
# protoc emits 6 leading comment/metadata lines; strip through the docstring.
sed -n '7,$p' "$WORK/scip_pb2.py" >> "$REPO_ROOT/src/cairn/parsers/_scip_pb2.py"

echo
echo "✓ done. Now:"
echo "  - verify import:  uv run --extra scip python -c 'from cairn.parsers import _scip_pb2; _scip_pb2.Index()'"
echo "  - update pyproject.toml [scip] protobuf floor to >= ${PROTO_VER} if raised"
echo "  - commit _scip_pb2.py + pyproject.toml together"
