#!/usr/bin/env bash
# Regenerate src/cairn/parsers/_scip_pb2.py from upstream sourcegraph/scip's
# scip.proto. This is a DEV-ONLY step -- the generated stub is checked in so
# end users installing cairn-intel[scip] only need the `protobuf` runtime.
#
# Why this exists: no PyPI package ships Sourcegraph SCIP protobuf bindings.
# (The `scip` name on PyPI is an unrelated bioimaging library.) We vendor a
# generated stub instead, paired with the real `protobuf` runtime package --
# the same approach googleapis-common-protos uses.
#
# Usage:
#   scripts/regen_scip_pb2.sh [commit-sha]     # default: upstream HEAD
#
# After regenerating:
#   1. Re-pin the [scip] extra's `protobuf` floor in pyproject.toml to >= the
#      version ValidateProtobufRuntimeVersion() requires (printed below).
#   2. Update the provenance comment at the top of _scip_pb2.py with the new
#      commit SHA + generator versions.
#   3. Commit _scip_pb2.py + pyproject.toml together -- never let them drift.
set -euo pipefail

COMMIT="${1:-HEAD}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "→ fetching scip.proto @ $COMMIT"
URL="https://raw.githubusercontent.com/sourcegraph/scip/${COMMIT}/scip.proto"
if [ "$COMMIT" = "HEAD" ]; then
    curl -fsSL "$URL" -o "$WORK/scip.proto"
    # Resolve HEAD to a SHA for the provenance pin.
    SHA="$(curl -fsSL "https://api.github.com/repos/sourcegraph/scip/commits?path=scip.proto&per_page=1" \
           | python3 -c "import sys,json;print(json.load(sys.stdin)[0]['sha'])")"
else
    URL="https://raw.githubusercontent.com/sourcegraph/scip/${COMMIT}/scip.proto"
    curl -fsSL "$URL" -o "$WORK/scip.proto"
    SHA="$COMMIT"
fi
echo "  resolved SHA: $SHA"

echo "→ generating _scip_pb2.py (needs grpcio-tools)"
( cd "$WORK" && python3 -m grpc_tools.protoc -I. --python_out=. scip.proto )

echo "→ installing to $REPO_ROOT/src/cairn/parsers/_scip_pb2.py"
# Preserve the provenance header; protoc's output starts with its own header
# we replace wholesale.
PROTO_VER="$(python3 -c 'import google.protobuf; print(google.protobuf.__version__)')"
GRPC_TOOLS_VER="$(python3 -c 'import grpc_tools; print(grpc_tools.__version__)' 2>/dev/null || echo 'unknown')"

cat > "$REPO_ROOT/src/cairn/parsers/_scip_pb2.py" <<HEADER
# -*- coding: utf-8 -*-
# Generated by protoc; DO NOT EDIT; source: scip.proto; protobuf ${PROTO_VER}.
# Vendored from sourcegraph/scip@${SHA} with grpcio-tools ${GRPC_TOOLS_VER}; regenerate via scripts/regen_scip_pb2.sh.
HEADER
# Append the body of protoc's output (everything after its header comment).
# The splice starts at the detected first non-comment, non-blank line (the
# module docstring), so any header length within the expected range splices
# correctly; the range guard below fails loudly on unexpected protoc drift.
# `|| true` keeps this set -euo pipefail safe: grep returns 1 on no match
# (an all-comment file), which would otherwise abort before the empty-check.
FIRST_BODY="$(grep -vn '^#\|^$' "$WORK/scip_pb2.py" | head -1 | cut -d: -f1 || true)"
if [ -z "$FIRST_BODY" ]; then
    echo "ERROR: $WORK/scip_pb2.py has no non-comment body -- inspect and update the sed line number." >&2
    exit 1
fi
if [ "$FIRST_BODY" -lt 6 ] || [ "$FIRST_BODY" -gt 8 ]; then
    echo "ERROR: protoc header shape changed (first body line at $FIRST_BODY, expected 6-8). Inspect $WORK/scip_pb2.py and update the sed line number." >&2
    exit 1
fi
sed -n "${FIRST_BODY},\$p" "$WORK/scip_pb2.py" >> "$REPO_ROOT/src/cairn/parsers/_scip_pb2.py"

echo
echo "✓ done. Now:"
echo "  - verify import:  uv run --extra scip python -c 'from cairn.parsers import _scip_pb2; _scip_pb2.Index()'"
echo "  - update pyproject.toml [scip] protobuf floor to >= ${PROTO_VER} if raised"
echo "  - commit _scip_pb2.py + pyproject.toml together"
